### ISSUE TITLE
can't use

### ISSUE THREAD

**Issue by muei** [stuartnelson3/golang-flowjs-upload#1]
::1 - - [25/Jun/2014:17:19:22 +0800] "GET /upload?flowChunkNumber=1&flowChunkSiz
e=10485760&flowCurrentChunkSize=322132&flowTotalSize=322132&flowIdentifier=32213
2-1jpg&flowFilename=%E8%B0%83%E7%A0%94%E4%BC%9A%E5%91%98%E7%95%8C%E9%9D%A21.jpg&
flowRelativePath=%E8%B0%83%E7%A0%94%E4%BC%9A%E5%91%98%E7%95%8C%E9%9D%A21.jpg&flo
wTotalChunks=1 HTTP/1.1" 500 103
::1 - - [25/Jun/2014:17:19:22 +0800] "POST /upload HTTP/1.1" 0 0
::1 - - [25/Jun/2014:17:20:54 +0800] "GET /upload?flowChunkNumber=1&flowChunkSiz
e=10485760&flowCurrentChunkSize=322132&flowTotalSize=322132&flowIdentifier=32213
2-43453jpg&flowFilename=43453.jpg&flowRelativePath=43453.jpg&flowTotalChunks=1 H
TTP/1.1" 500 89

**Comment by kakacjz** [comment]
can not use
